"""Initial migration

Revision ID: 2cbae5127dc7
Revises: 
Create Date: 2025-08-05 12:59:33.511076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbae5127dc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_series_nombre'), 'series', ['nombre'], unique=False)
    op.create_table('subseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subseries_id'), 'subseries', ['id'], unique=False)
    op.create_index(op.f('ix_subseries_nombre'), 'subseries', ['nombre'], unique=False)
    op.create_table('tipos_documentales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('subserie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subserie_id'], ['subseries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_documentales_id'), 'tipos_documentales', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_documentales_nombre'), 'tipos_documentales', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_documentales_nombre'), table_name='tipos_documentales')
    op.drop_index(op.f('ix_tipos_documentales_id'), table_name='tipos_documentales')
    op.drop_table('tipos_documentales')
    op.drop_index(op.f('ix_subseries_nombre'), table_name='subseries')
    op.drop_index(op.f('ix_subseries_id'), table_name='subseries')
    op.drop_table('subseries')
    op.drop_index(op.f('ix_series_nombre'), table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
